# Generated by Django 4.2.11 on 2026-01-07 08:01

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='discussionreply',
            options={'ordering': ['-is_answer', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='resourcerating',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='core_course_code_833bcc_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='core_course_departm_86923c_idx',
        ),
        migrations.RemoveIndex(
            model_name='discussion',
            name='core_discus_course__fa1a16_idx',
        ),
        migrations.RemoveIndex(
            model_name='discussionreply',
            name='core_discus_discuss_d025af_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='core_resour_course__0fc774_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='core_resour_resourc_9985a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='resourcerating',
            name='core_resour_resourc_51d913_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('VIDEO', 'Video'), ('LINK', 'Link'), ('NOTE', 'Notes'), ('ASSIGNMENT', 'Assignment')], default='PDF', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcerating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='resourcerating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='course',
            table='core_course',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='core_customuser',
        ),
        migrations.AlterModelTable(
            name='discussion',
            table='core_discussion',
        ),
        migrations.AlterModelTable(
            name='discussionreply',
            table='core_discussionreply',
        ),
        migrations.AlterModelTable(
            name='resource',
            table='core_resource',
        ),
        migrations.AlterModelTable(
            name='resourcerating',
            table='core_resourcerating',
        ),
    ]
