# Generated by Django 4.2.11 on 2026-01-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_reply_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('thread', 'Thread'), ('reply', 'Reply')], default='thread', max_length=20),
        ),
    ]
